### PR TITLE
symbol bug and pycache ignore folder

### PR DESCRIPTION
**Pull request by mattfisc**
i fixed the symbol bug
added ignore to pycache

### CODE REVIEW

**Review by RafaelZasas — COMMENTED** [review]
I actually already fixed it.
Also added documentation 
also added Unit Testing.

**Review by RafaelZasas — CHANGES_REQUESTED** [review]
Have a look at the tab that says +- Files Changed under this pull request and see if there's any changes that you didn't expect/ intend for

**Comment by mattfisc** [comment]
closed bug already fixed.

**Comment by mattfisc** [comment]
bug already fixed closing pull

**Pull request closed without merging**
